<?php
define('APP_ACCESS', true);
require_once __DIR__ . '/../../includes/config.php';
require_once __DIR__ . '/../../includes/Database.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../includes/session.php';
require_once __DIR__ . '/../../includes/security.php';
require_once __DIR__ . '/../../models/Report.php';

requireLogin();
requireAnyRole(['admin', 'cashier']);

$pageTitle = 'Reports';

// Date range filter
$dateFrom = $_GET['from'] ?? date('Y-m-d', strtotime('-30 days'));
$dateTo = $_GET['to'] ?? date('Y-m-d');

if (!strtotime($dateFrom)) {
    $dateFrom = date('Y-m-d', strtotime('-30 days'));
}
if (!strtotime($dateTo)) {
    $dateTo = date('Y-m-d');
}
if ($dateFrom > $dateTo) {
    $dateFrom = date('Y-m-d', strtotime('-30 days'));
    $dateTo = date('Y-m-d');
}

$reportModel = new Report();
$incomeReport = $reportModel->getIncomeReport($dateFrom, $dateTo);
$serviceStats = $reportModel->getServiceTypeStats($dateFrom, $dateTo);
$paymentMethods = $reportModel->getPaymentMethodStats($dateFrom, $dateTo);
$paymentSummary = $reportModel->getPaymentStatusSummary();
$statusSummary = $reportModel->getJobOrderStatusSummary();
$topCustomers = $reportModel->getTopCustomers(10);
$recentActivity = $reportModel->getRecentActivity(8);

$totalOrders = array_sum(array_column($incomeReport, 'job_orders_count'));
$totalIncome = array_sum(array_column($incomeReport, 'total_income'));
$paidIncome = array_sum(array_column($incomeReport, 'paid_income'));
$pendingIncome = array_sum(array_column($incomeReport, 'pending_income'));

if (($_GET['export'] ?? '') === 'excel') {
    $db = Database::getInstance();
    $jobOrderDetails = $db->fetchAll(
        "SELECT
            jo.job_order_number,
            jo.created_at,
            jo.status,
            jo.payment_status,
            jo.total_amount,
            jo.partial_amount,
            c.full_name AS customer_name,
            c.phone AS customer_phone,
            v.brand,
            v.model,
            v.plate_number
         FROM job_orders jo
         LEFT JOIN customers c ON jo.customer_id = c.id
         LEFT JOIN vehicles v ON jo.vehicle_id = v.id
         WHERE DATE(jo.created_at) BETWEEN ? AND ?
         ORDER BY jo.created_at DESC",
        [$dateFrom, $dateTo]
    );

    $safeFrom = preg_replace('/[^0-9\-]/', '', $dateFrom);
    $safeTo = preg_replace('/[^0-9\-]/', '', $dateTo);
    $filename = "autodok_reports_{$safeFrom}_to_{$safeTo}.xls";

    header('Content-Type: application/vnd.ms-excel; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');

    echo "<html><head><meta charset='UTF-8'><style>";
    echo "body{font-family:Calibri,Arial,sans-serif;font-size:12px;color:#111;}";
    echo ".report-title{font-size:22px;font-weight:700;margin:0 0 6px 0;color:#1f2937;}";
    echo ".report-sub{font-size:12px;color:#4b5563;margin:0 0 12px 0;}";
    echo ".meta{margin-bottom:10px;}";
    echo ".meta td{padding:4px 8px;border:none;}";
    echo ".note{background:#f8fafc;border:1px solid #dbe3ee;padding:8px 10px;margin:8px 0 14px 0;color:#334155;}";
    echo ".section{font-size:15px;font-weight:700;color:#1f2937;margin:14px 0 6px 0;}";
    echo "table{border-collapse:collapse;width:100%;margin-bottom:14px;}";
    echo "th,td{border:1px solid #d1d5db;padding:6px 8px;vertical-align:middle;}";
    echo "th{background:#eef2f7;color:#111827;font-weight:700;text-align:left;white-space:nowrap;}";
    echo "tr:nth-child(even) td{background:#fafafa;}";
    echo ".text-right{text-align:right;}";
    echo ".muted{color:#6b7280;}";
    echo "</style></head><body>";

    echo "<div class='report-title'>The Autodok Reports</div>";
    echo "<div class='report-sub'>Exported financial and operational report</div>";
    echo "<table class='meta'>";
    echo "<tr><td><strong>Period:</strong></td><td>" . escape($dateFrom) . " to " . escape($dateTo) . "</td></tr>";
    echo "<tr><td><strong>Generated At:</strong></td><td>" . escape(date('Y-m-d h:i A')) . "</td></tr>";
    echo "<tr><td><strong>Generated By:</strong></td><td>" . escape($_SESSION['full_name'] ?? $_SESSION['username'] ?? 'System') . "</td></tr>";
    echo "</table>";
    echo "<div class='note'><strong>How totals are computed:</strong> <span class='muted'>Paid includes fully paid orders plus partial amounts from partially paid orders. Pending includes full pending orders plus remaining balances from partially paid orders.</span></div>";

    echo "<div class='section'>1. Executive Summary</div>";
    echo "<table>";
    echo "<tr><th>Total Job Orders</th><th>Total Income (PHP)</th><th>Paid Income (PHP)</th><th>Pending Income (PHP)</th></tr>";
    echo "<tr>";
    echo "<td class='text-right'>" . number_format($totalOrders) . "</td>";
    echo "<td class='text-right'>" . number_format((float)$totalIncome, 2) . "</td>";
    echo "<td class='text-right'>" . number_format((float)$paidIncome, 2) . "</td>";
    echo "<td class='text-right'>" . number_format((float)$pendingIncome, 2) . "</td>";
    echo "</tr></table>";

    echo "<div class='section'>2. Job Orders Details</div>";
    echo "<table><tr>";
    echo "<th>JO #</th><th>Date</th><th>Customer</th><th>Phone</th><th>Vehicle</th><th>Plate</th><th>Status</th><th>Payment Status</th><th class='text-right'>Total (PHP)</th><th class='text-right'>Paid (PHP)</th><th class='text-right'>Pending (PHP)</th>";
    echo "</tr>";
    if (empty($jobOrderDetails)) {
        echo "<tr><td colspan='11'>No job orders for this range</td></tr>";
    } else {
        foreach ($jobOrderDetails as $row) {
            $rowTotal = (float)($row['total_amount'] ?? 0);
            $rowPartial = (float)($row['partial_amount'] ?? 0);
            $rowPayment = (string)($row['payment_status'] ?? 'pending');
            $rowPaid = 0.0;
            $rowPending = 0.0;

            if ($rowPayment === 'paid') {
                $rowPaid = $rowTotal;
            } elseif ($rowPayment === 'partial') {
                $rowPaid = max(0, min($rowPartial, $rowTotal));
                $rowPending = max(0, $rowTotal - $rowPaid);
            } else {
                $rowPending = $rowTotal;
            }

            echo "<tr>";
            echo "<td>" . escape($row['job_order_number']) . "</td>";
            echo "<td>" . escape(date('Y-m-d H:i', strtotime($row['created_at']))) . "</td>";
            echo "<td>" . escape($row['customer_name'] ?? 'Unknown') . "</td>";
            echo "<td>" . escape($row['customer_phone'] ?? '—') . "</td>";
            echo "<td>" . escape(trim(($row['brand'] ?? '') . ' ' . ($row['model'] ?? ''))) . "</td>";
            echo "<td>" . escape($row['plate_number'] ?? '—') . "</td>";
            echo "<td>" . escape(ucwords(str_replace('_', ' ', $row['status'] ?? 'pending'))) . "</td>";
            echo "<td>" . escape(ucwords(str_replace('_', ' ', $rowPayment))) . "</td>";
            echo "<td class='text-right'>" . number_format($rowTotal, 2) . "</td>";
            echo "<td class='text-right'>" . number_format($rowPaid, 2) . "</td>";
            echo "<td class='text-right'>" . number_format($rowPending, 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>3. Income Trend</div>";
    echo "<table><tr><th>Date</th><th class='text-right'>Job Orders</th><th class='text-right'>Total Income (PHP)</th><th class='text-right'>Paid Income (PHP)</th><th class='text-right'>Pending Income (PHP)</th></tr>";
    if (empty($incomeReport)) {
        echo "<tr><td colspan='5'>No data for this range</td></tr>";
    } else {
        foreach ($incomeReport as $row) {
            echo "<tr>";
            echo "<td>" . escape($row['date']) . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['job_orders_count']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_income'], 2) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['paid_income'], 2) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['pending_income'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>4. Service Type Revenue</div>";
    echo "<table><tr><th>Service Type</th><th class='text-right'>Orders</th><th class='text-right'>Revenue (PHP)</th></tr>";
    if (empty($serviceStats)) {
        echo "<tr><td colspan='3'>No data for this range</td></tr>";
    } else {
        foreach ($serviceStats as $row) {
            echo "<tr>";
            echo "<td>" . escape($row['service_name'] ?? $row['service_type'] ?? 'Unknown') . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['count']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_revenue'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>5. Payment Method Breakdown</div>";
    echo "<table><tr><th>Method</th><th class='text-right'>Orders</th><th class='text-right'>Amount (PHP)</th></tr>";
    if (empty($paymentMethods)) {
        echo "<tr><td colspan='3'>No payment data for this range</td></tr>";
    } else {
        foreach ($paymentMethods as $row) {
            echo "<tr>";
            echo "<td>" . escape($row['payment_method'] ?? 'Unknown') . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['count']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_amount'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>6. Job Order Status Summary</div>";
    echo "<table><tr><th>Status</th><th class='text-right'>Count</th><th class='text-right'>Total (PHP)</th></tr>";
    if (empty($statusSummary)) {
        echo "<tr><td colspan='3'>No status summary available</td></tr>";
    } else {
        foreach ($statusSummary as $row) {
            echo "<tr>";
            echo "<td>" . escape(ucwords(str_replace('_', ' ', $row['status']))) . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['count']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_amount'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>7. Payment Status Summary</div>";
    echo "<table><tr><th>Payment Status</th><th class='text-right'>Orders</th><th class='text-right'>Total (PHP)</th></tr>";
    if (empty($paymentSummary)) {
        echo "<tr><td colspan='3'>No payment summary available</td></tr>";
    } else {
        foreach ($paymentSummary as $row) {
            echo "<tr>";
            echo "<td>" . escape(ucwords(str_replace('_', ' ', $row['payment_status']))) . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['count']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_amount'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>8. Top Customers</div>";
    echo "<table><tr><th>Customer</th><th>Phone</th><th class='text-right'>Visits</th><th class='text-right'>Spent (PHP)</th></tr>";
    if (empty($topCustomers)) {
        echo "<tr><td colspan='4'>No customer activity yet</td></tr>";
    } else {
        foreach ($topCustomers as $row) {
            echo "<tr>";
            echo "<td>" . escape($row['customer_name']) . "</td>";
            echo "<td>" . escape($row['customer_phone']) . "</td>";
            echo "<td class='text-right'>" . number_format((int)$row['total_visits']) . "</td>";
            echo "<td class='text-right'>" . number_format((float)$row['total_spent'], 2) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "<div class='section'>9. Recent Activity</div>";
    echo "<table><tr><th>Action</th><th>Description</th><th>User</th><th>Date</th></tr>";
    if (empty($recentActivity)) {
        echo "<tr><td colspan='4'>No recent activity found</td></tr>";
    } else {
        foreach ($recentActivity as $activity) {
            echo "<tr>";
            echo "<td>" . escape($activity['action']) . "</td>";
            echo "<td>" . escape($activity['description']) . "</td>";
            echo "<td>" . escape($activity['username'] ?? 'System') . "</td>";
            echo "<td>" . escape(date('F d, Y h:i A', strtotime($activity['created_at']))) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    echo "</body></html>";
    exit;
}

include __DIR__ . '/../partials/header.php';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h4 class="mb-0">Reports</h4>
        <p class="text-muted small mb-0">View business performance, payment status, and service statistics.</p>
    </div>
    <form class="row gx-2 gy-2 align-items-center" method="GET" action="">
        <div class="col-auto">
            <input type="date" class="form-control" name="from" value="<?php echo escape($dateFrom); ?>">
        </div>
        <div class="col-auto">
            <input type="date" class="form-control" name="to" value="<?php echo escape($dateTo); ?>">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Apply</button>
        </div>
        <div class="col-auto">
            <button type="submit" name="export" value="excel" class="btn btn-success">Export Excel</button>
        </div>
    </form>
</div>

<div class="row g-4 mb-4">
    <div class="col-md-3">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted mb-1 small">Report Period</p>
                <h5 class="mb-0"><?php echo escape($dateFrom); ?> — <?php echo escape($dateTo); ?></h5>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted mb-1 small">Job Orders</p>
                <h3 class="mb-0"><?php echo number_format($totalOrders); ?></h3>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted mb-1 small">Total Income</p>
                <h3 class="mb-0">₱ <?php echo number_format($totalIncome, 2); ?></h3>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card h-100">
            <div class="card-body">
                <p class="text-muted mb-1 small">Paid / Pending</p>
                <h5 class="mb-0">₱ <?php echo number_format($paidIncome, 2); ?> / ₱ <?php echo number_format($pendingIncome, 2); ?></h5>
            </div>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
                <h5 class="card-title mb-0">Income Trend</h5>
                <p class="text-muted small mb-0">Daily income between selected dates.</p>
            </div>
        </div>
        <div>
            <canvas id="incomeTrendChart" style="min-height:240px;"></canvas>
        </div>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-lg-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Service Type Revenue</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Service Type</th>
                                <th class="text-end">Orders</th>
                                <th class="text-end">Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($serviceStats)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No data for this range</td></tr>
                            <?php else: ?>
                                <?php foreach ($serviceStats as $row): ?>
                                    <tr>
                                        <td><?php echo escape($row['service_name'] ?? $row['service_type'] ?? 'Unknown'); ?></td>
                                        <td class="text-end"><?php echo number_format($row['count']); ?></td>
                                        <td class="text-end">₱ <?php echo number_format($row['total_revenue'], 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Payment Method Breakdown</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Method</th>
                                <th class="text-end">Orders</th>
                                <th class="text-end">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($paymentMethods)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No paid orders for this range</td></tr>
                            <?php else: ?>
                                <?php foreach ($paymentMethods as $row): ?>
                                    <tr>
                                        <td><?php echo escape($row['payment_method'] ?? 'Unknown'); ?></td>
                                        <td class="text-end"><?php echo number_format($row['count']); ?></td>
                                        <td class="text-end">₱ <?php echo number_format($row['total_amount'], 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-lg-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Job Order Status Summary</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th class="text-end">Count</th>
                                <th class="text-end">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($statusSummary)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No status summary available</td></tr>
                            <?php else: ?>
                                <?php foreach ($statusSummary as $row): ?>
                                    <tr>
                                        <td><?php echo escape(ucwords(str_replace('_', ' ', $row['status']))); ?></td>
                                        <td class="text-end"><?php echo number_format($row['count']); ?></td>
                                        <td class="text-end">₱ <?php echo number_format($row['total_amount'], 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Top Customers</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                <th class="text-end">Visits</th>
                                <th class="text-end">Spent</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($topCustomers)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No customer activity yet</td></tr>
                            <?php else: ?>
                                <?php foreach ($topCustomers as $row): ?>
                                    <tr>
                                        <td><?php echo escape($row['customer_name']); ?> <span class="text-muted small d-block"><?php echo escape($row['customer_phone']); ?></span></td>
                                        <td class="text-end"><?php echo number_format($row['total_visits']); ?></td>
                                        <td class="text-end">₱ <?php echo number_format($row['total_spent'], 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-lg-12">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Payment Status Summary</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Payment Status</th>
                                <th class="text-end">Orders</th>
                                <th class="text-end">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($paymentSummary)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No payment data available</td></tr>
                            <?php else: ?>
                                <?php foreach ($paymentSummary as $row): ?>
                                    <tr>
                                        <td><?php echo escape(ucwords(str_replace('_', ' ', $row['payment_status']))); ?></td>
                                        <td class="text-end"><?php echo number_format($row['count']); ?></td>
                                        <td class="text-end">₱ <?php echo number_format($row['total_amount'], 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-lg-12">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">Recent Activity</h5>
                <div class="table-responsive">
                    <table class="table table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Activity</th>
                                <th>User</th>
                                <th class="text-end">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($recentActivity)): ?>
                                <tr><td colspan="3" class="text-center text-muted">No recent activity found</td></tr>
                            <?php else: ?>
                                <?php foreach ($recentActivity as $activity): ?>
                                    <tr>
                                        <td>
                                            <strong><?php echo escape($activity['action']); ?></strong>
                                            <div class="text-muted small"><?php echo escape($activity['description']); ?></div>
                                        </td>
                                        <td><?php echo escape($activity['username'] ?? 'System'); ?></td>
                                        <td class="text-end"><?php echo escape(date('F d, Y h:i A', strtotime($activity['created_at']))); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
(function() {
    const reportData = <?php echo json_encode($incomeReport); ?>;
    const labels = reportData.map(item => item.date);
    const totalIncomeData = reportData.map(item => parseFloat(item.total_income) || 0);
    const paidIncomeData = reportData.map(item => parseFloat(item.paid_income) || 0);
    const pendingIncomeData = reportData.map(item => parseFloat(item.pending_income) || 0);

    const ctx = document.getElementById('incomeTrendChart');
    if (ctx) {
        new Chart(ctx, {
            type: 'line',
            data: {
                labels,
                datasets: [
                    {
                        label: 'Total Income',
                        data: totalIncomeData,
                        borderColor: '#0d6efd',
                        backgroundColor: 'rgba(13,110,253,0.12)',
                        tension: 0.35,
                        fill: true,
                        pointRadius: 3
                    },
                    {
                        label: 'Paid Income',
                        data: paidIncomeData,
                        borderColor: '#198754',
                        backgroundColor: 'rgba(25,135,84,0.12)',
                        tension: 0.35,
                        fill: true,
                        pointRadius: 3
                    },
                    {
                        label: 'Pending Income',
                        data: pendingIncomeData,
                        borderColor: '#dc3545',
                        backgroundColor: 'rgba(220,53,69,0.12)',
                        tension: 0.35,
                        fill: true,
                        pointRadius: 3
                    }
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: { position: 'top' },
                    tooltip: { mode: 'index', intersect: false }
                },
                interaction: { mode: 'nearest', intersect: false },
                scales: {
                    x: { display: true, title: { display: false } },
                    y: { display: true, beginAtZero: true, title: { display: true, text: 'Amount (₱)' } }
                }
            }
        });
    }
})();
</script>

<?php include __DIR__ . '/../partials/footer.php'; ?>
